language: node_js
node_js:
  - "0.10"

before_script:
  - npm install -g grunt-cli
  - npm install
  - chmod +x ./node_modules/.bin/grunt
  - cd nightwatch
  - java -jar ./../assets/selenium-server-standalone-2.45.0.jar

script:
  - grunt --force
  - node nightwatch.js


