language: node_js
node_js:
  - "0.10"

before_script:
  - npm install -g grunt-cli
  - npm install
  - cd nightwatch

script:
  - grunt
  - npm test
  # - npm run-script coverage

after_success:
  # - cat ./lib-cov/lcov.info |coveralls

