language: node_js
node_js:
  - "0.10"

before_script:
  - npm install -g grunt-cli
  - npm install
  - chmod +x ./node_modules/.bin/grunt
  - cd nightwatch

script:
  - grunt --force
  - node nightwatch.js


